# --------------------------------------------------------
# --------------------------------------------------------
# --------------------------------------------------------
# --------------------------------------------------------
# --------------------------------------------------------
INSERT INTO `prefix_lstest_tests` VALUES (1,'CHAEA','es_utf8',1,1,0,1);
# --------------------------------------------------------
# --------------------------------------------------------
INSERT INTO `prefix_lstest_styles` VALUES (1,1,'Activo');
INSERT INTO `prefix_lstest_styles` VALUES (2,1,'Reflexivo');
INSERT INTO `prefix_lstest_styles` VALUES (3,1,'Teórico');
INSERT INTO `prefix_lstest_styles` VALUES (4,1,'Pragmático');
# --------------------------------------------------------
# --------------------------------------------------------
INSERT INTO `prefix_lstest_levels` VALUES (1,1,'Muy baja');
INSERT INTO `prefix_lstest_levels` VALUES (2,1,'Baja');
INSERT INTO `prefix_lstest_levels` VALUES (3,1,'Moderada');
INSERT INTO `prefix_lstest_levels` VALUES (4,1,'Alta');
INSERT INTO `prefix_lstest_levels` VALUES (5,1,'Muy alta');
# --------------------------------------------------------
# --------------------------------------------------------
INSERT INTO `prefix_lstest_thresholds` VALUES (1,1,1,0,6);
INSERT INTO `prefix_lstest_thresholds` VALUES (2,1,2,7,8);
INSERT INTO `prefix_lstest_thresholds` VALUES (3,1,3,9,12);
INSERT INTO `prefix_lstest_thresholds` VALUES (4,1,4,13,14);
INSERT INTO `prefix_lstest_thresholds` VALUES (5,1,5,15,20);
INSERT INTO `prefix_lstest_thresholds` VALUES (6,2,1,0,10);
INSERT INTO `prefix_lstest_thresholds` VALUES (7,2,2,11,13);
INSERT INTO `prefix_lstest_thresholds` VALUES (8,2,3,14,17);
INSERT INTO `prefix_lstest_thresholds` VALUES (9,2,4,18,19);
INSERT INTO `prefix_lstest_thresholds` VALUES (10,2,5,20,20);
INSERT INTO `prefix_lstest_thresholds` VALUES (11,3,1,0,6);
INSERT INTO `prefix_lstest_thresholds` VALUES (12,3,2,7,9);
INSERT INTO `prefix_lstest_thresholds` VALUES (13,3,3,10,13);
INSERT INTO `prefix_lstest_thresholds` VALUES (14,3,4,14,15);
INSERT INTO `prefix_lstest_thresholds` VALUES (15,3,5,16,20);
INSERT INTO `prefix_lstest_thresholds` VALUES (16,4,1,0,8);
INSERT INTO `prefix_lstest_thresholds` VALUES (17,4,2,9,10);
INSERT INTO `prefix_lstest_thresholds` VALUES (18,4,3,11,13);
INSERT INTO `prefix_lstest_thresholds` VALUES (19,4,4,14,15);
INSERT INTO `prefix_lstest_thresholds` VALUES (20,4,5,16,20);
# --------------------------------------------------------
# --------------------------------------------------------
INSERT INTO `prefix_lstest_answers` VALUES (1,1,'Poco de acuerdo');
INSERT INTO `prefix_lstest_answers` VALUES (2,1,'Bastante de acuerdo');
# --------------------------------------------------------
# --------------------------------------------------------
INSERT INTO `prefix_lstest_items` VALUES (1,1,4,'Tengo fama de decir lo que pienso claramente y sin rodeos.');
INSERT INTO `prefix_lstest_items` VALUES (2,1,3,'Estoy seguro/a de lo que es bueno y lo que es malo, lo que esta bien y lo que esta mal.');
INSERT INTO `prefix_lstest_items` VALUES (3,1,1,'Muchas veces actúo sin mirar las consecuencias.');
INSERT INTO `prefix_lstest_items` VALUES (4,1,3,'Normalmente trato de resolver los problemas metódicamente y paso a paso.');
INSERT INTO `prefix_lstest_items` VALUES (5,1,1,'Creo que los formalismos coartan y limitan la actuación libre de las personas.');
INSERT INTO `prefix_lstest_items` VALUES (6,1,3,'Me interesa saber cuales son los sistemas de valores de los demás y con que criterios actúan.');
INSERT INTO `prefix_lstest_items` VALUES (7,1,1,'Pienso que el actuar intuitivamente puede ser siempre tan valido como actuar reflexivamente.');
INSERT INTO `prefix_lstest_items` VALUES (8,1,4,'Creo que lo más importante es que las cosas funcionen.');
INSERT INTO `prefix_lstest_items` VALUES (9,1,1,'Procuro estar al tanto de lo que ocurre aquí y ahora.');
INSERT INTO `prefix_lstest_items` VALUES (10,1,2,'Disfruto cuando tengo tiempo para preparar mi trabajo y realizarlo a conciencia.');
INSERT INTO `prefix_lstest_items` VALUES (11,1,3,'Estoy a gusto siguiendo un orden, en las comidas, en el estudio, haciendo ejercicio regularmente.');
INSERT INTO `prefix_lstest_items` VALUES (12,1,4,'Cuando escucho una nueva idea enseguida comienzo a pensar como ponerla en práctica.');
INSERT INTO `prefix_lstest_items` VALUES (13,1,1,'Prefiero las ideas originales y novedosas aunque no sean prácticas.');
INSERT INTO `prefix_lstest_items` VALUES (14,1,4,'Admito y me ajusto a las normas solo si me sirven para lograr mis objetivos.');
INSERT INTO `prefix_lstest_items` VALUES (15,1,3,'Normalmente encajo bien con personas reflexivas, y me cuesta sintonizar con personas demasiado espontáneas, imprevisibles.');
INSERT INTO `prefix_lstest_items` VALUES (16,1,2,'Escucho con más frecuencia que hablo.');
INSERT INTO `prefix_lstest_items` VALUES (17,1,3,'Prefiero las cosas estructuradas a las desordenadas.');
INSERT INTO `prefix_lstest_items` VALUES (18,1,2,'Cuando poseo cualquier información, trato de interpretarla bien antes de manifestar alguna conclusión.');
INSERT INTO `prefix_lstest_items` VALUES (19,1,2,'Antes de hacer algo estudio con cuidado sus ventajas e inconvenientes.');
INSERT INTO `prefix_lstest_items` VALUES (20,1,1,'Crezco con el reto de hacer algo nuevo y diferente.');
INSERT INTO `prefix_lstest_items` VALUES (21,1,3,'Casi siempre procuro ser coherente con mis criterios y sistemas de valores. Tengo principios y los sigo.');
INSERT INTO `prefix_lstest_items` VALUES (22,1,4,'Cuando hay una discusión no me gusta ir con rodeos.');
INSERT INTO `prefix_lstest_items` VALUES (23,1,3,'Me disgusta implicarme afectivamente en mi ambiente de trabajo. Prefiero mantener relaciones distantes.');
INSERT INTO `prefix_lstest_items` VALUES (24,1,4,'Me gustan más las personas realistas y concretas que las teóricas.');
INSERT INTO `prefix_lstest_items` VALUES (25,1,3,'Me gusta ser creativo/a, romper estructuras.');
INSERT INTO `prefix_lstest_items` VALUES (26,1,1,'Me siento a gusto con personas espontáneas y divertidas.');
INSERT INTO `prefix_lstest_items` VALUES (27,1,1,'La mayoría de las veces expreso abiertamente cómo me siento.');
INSERT INTO `prefix_lstest_items` VALUES (28,1,2,'Me gusta analizar y dar vueltas a las cosas.');
INSERT INTO `prefix_lstest_items` VALUES (29,1,3,'Me molesta que la gente no se tome en serio las cosas.');
INSERT INTO `prefix_lstest_items` VALUES (30,1,4,'Me atrae experimentar y practicar las últimas técnicas y novedades.');
INSERT INTO `prefix_lstest_items` VALUES (31,1,2,'Soy cauteloso/a a la hora de sacar conclusiones.');
INSERT INTO `prefix_lstest_items` VALUES (32,1,2,'Prefiero contar con el mayor número de fuentes de información. Cuantos más datos reúna para reflexionar, mejor.');
INSERT INTO `prefix_lstest_items` VALUES (33,1,3,'Tiendo a ser perfeccionista.');
INSERT INTO `prefix_lstest_items` VALUES (34,1,2,'Prefiero oír las opiniones de los demás antes de exponer la mía.');
INSERT INTO `prefix_lstest_items` VALUES (35,1,1,'Me gusta afrontar la vida espontáneamente y no tener que planificar todo previamente.');
INSERT INTO `prefix_lstest_items` VALUES (36,1,2,'En las discusiones me gusta observar cómo actúan los demás participantes.');
INSERT INTO `prefix_lstest_items` VALUES (37,1,1,'Me siento incómodo/a con las personas calladas y demasiado analíticas.');
INSERT INTO `prefix_lstest_items` VALUES (38,1,4,'Juzgo con frecuencia las ideas de los demás por su valor práctico.');
INSERT INTO `prefix_lstest_items` VALUES (39,1,2,'Me agobio si me obligan a acelerar mucho el trabajo para cumplir un plazo.');
INSERT INTO `prefix_lstest_items` VALUES (40,1,4,'En las reuniones apoyo las ideas prácticas y realistas.');
INSERT INTO `prefix_lstest_items` VALUES (41,1,1,'Es mejor gozar del momento presente que deleitarse pensando en el pasado o en el futuro.');
INSERT INTO `prefix_lstest_items` VALUES (42,1,2,'Me molestan las personas que siempre desean apresurar las cosas.');
INSERT INTO `prefix_lstest_items` VALUES (43,1,1,'Aporto ideas nuevas y espontáneas en los grupos de discusión.');
INSERT INTO `prefix_lstest_items` VALUES (44,1,2,'Pienso que son más conscientes las decisiones fundamentadas en un minucioso análisis que las basadas en la intuición.');
INSERT INTO `prefix_lstest_items` VALUES (45,1,3,'Detecto frecuentemente la inconsistencia y puntos débiles en las argumentaciones de los demás.');
INSERT INTO `prefix_lstest_items` VALUES (46,1,1,'Creo que es preciso saltarse las normas muchas más veces que cumplirlas.');
INSERT INTO `prefix_lstest_items` VALUES (47,1,4,'A menudo caigo en cuenta de otras formas mejores y más prácticas de hacer las cosas.');
INSERT INTO `prefix_lstest_items` VALUES (48,1,1,'En conjunto hablo más que escucho.');
INSERT INTO `prefix_lstest_items` VALUES (49,1,2,'Prefiero distanciarme de los hechos y observarlos desde otras perspectivas.');
INSERT INTO `prefix_lstest_items` VALUES (50,1,3,'Estoy convencido/a que debe imponerse la lógica y el razonamiento.');
INSERT INTO `prefix_lstest_items` VALUES (51,1,1,'Me gusta buscar nuevas experiencias.');
INSERT INTO `prefix_lstest_items` VALUES (52,1,4,'Me gusta experimentar y aplicar las cosas.');
INSERT INTO `prefix_lstest_items` VALUES (53,1,4,'Pienso que debemos llegar pronto al grano, al meollo de los temas.');
INSERT INTO `prefix_lstest_items` VALUES (54,1,3,'Siempre trato de conseguir conclusiones e ideas claras.');
INSERT INTO `prefix_lstest_items` VALUES (55,1,2,'Prefiero discutir cuestiones concretas y no perder el tiempo con charlas vacías.');
INSERT INTO `prefix_lstest_items` VALUES (56,1,4,'Me impaciento cuando me dan explicaciones irrelevantes e incoherentes.');
INSERT INTO `prefix_lstest_items` VALUES (57,1,4,'Compruebo antes si las cosas funcionan realmente.');
INSERT INTO `prefix_lstest_items` VALUES (58,1,2,'Hago varios borradores antes de la redacción definitiva de un trabajo.');
INSERT INTO `prefix_lstest_items` VALUES (59,1,4,'Soy consciente de que en las discusiones ayudo a mantener a los demás centrados en el tema, evitando divagaciones.');
INSERT INTO `prefix_lstest_items` VALUES (60,1,3,'Observo que, con frecuencia, soy uno/a de los/as más objetivos/as y desapasionados/as en las discusiones.');
INSERT INTO `prefix_lstest_items` VALUES (61,1,1,'Cuando algo va mal le quito importancia y trato de hacerlo mejor.');
INSERT INTO `prefix_lstest_items` VALUES (62,1,4,'Rechazo ideas originales y espontáneas si no las veo prácticas.');
INSERT INTO `prefix_lstest_items` VALUES (63,1,2,'Me gusta sopesar diversas alternativas antes de tomar una decisión.');
INSERT INTO `prefix_lstest_items` VALUES (64,1,3,'Con frecuencia miro hacia delante para prever el futuro.');
INSERT INTO `prefix_lstest_items` VALUES (65,1,2,'En los debates y discusiones prefiero desempeñar un papel secundario antes que ser el/la líder o el/la que más participa.');
INSERT INTO `prefix_lstest_items` VALUES (66,1,3,'Me molestan las personas que no actúan con lógica.');
INSERT INTO `prefix_lstest_items` VALUES (67,1,1,'Me resulta incomodo tener que planificar y prever las cosas.');
INSERT INTO `prefix_lstest_items` VALUES (68,1,4,'Creo que el fin justifica los medios en muchos casos.');
INSERT INTO `prefix_lstest_items` VALUES (69,1,2,'Suelo reflexionar sobre los asuntos y problemas.');
INSERT INTO `prefix_lstest_items` VALUES (70,1,2,'El trabajar a conciencia me llena de satisfacción y orgullo.');
INSERT INTO `prefix_lstest_items` VALUES (71,1,3,'Ante los acontecimientos trato de descubrir los principios y teorías en que se basan.');
INSERT INTO `prefix_lstest_items` VALUES (72,1,4,'Con tal de conseguir el objetivo que pretendo soy capaz de herir sentimientos ajenos.');
INSERT INTO `prefix_lstest_items` VALUES (73,1,4,'No me importa hacer todo lo necesario para que sea efectivo  mi trabajo.');
INSERT INTO `prefix_lstest_items` VALUES (74,1,1,'Con frecuencia soy una de las personas que más anima las fiestas.');
INSERT INTO `prefix_lstest_items` VALUES (75,1,1,'Me aburro enseguida con el trabajo metódico y minucioso.');
INSERT INTO `prefix_lstest_items` VALUES (76,1,4,'La gente con frecuencia cree que soy poco sensible a sus sentimientos.');
INSERT INTO `prefix_lstest_items` VALUES (77,1,1,'Suelo dejarme llevar por mis intuiciones.');
INSERT INTO `prefix_lstest_items` VALUES (78,1,3,'Si trabajo en grupo procuro que se siga un método y un orden.');
INSERT INTO `prefix_lstest_items` VALUES (79,1,2,'Con frecuencia me interesa averiguar lo que piensa la gente.');
INSERT INTO `prefix_lstest_items` VALUES (80,1,3,'Esquivo los temas subjetivos, ambiguos y poco claros.');
# --------------------------------------------------------
# --------------------------------------------------------
INSERT INTO `prefix_lstest_scores` VALUES (1,1,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (2,1,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (3,2,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (4,2,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (5,3,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (6,3,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (7,4,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (8,4,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (9,5,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (10,5,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (11,6,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (12,6,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (13,7,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (14,7,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (15,8,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (16,8,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (17,9,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (18,9,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (19,10,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (20,10,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (21,11,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (22,11,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (23,12,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (24,12,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (25,13,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (26,13,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (27,14,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (28,14,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (29,15,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (30,15,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (31,16,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (32,16,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (33,17,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (34,17,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (35,18,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (36,18,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (37,19,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (38,19,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (39,20,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (40,20,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (41,21,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (42,21,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (43,22,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (44,22,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (45,23,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (46,23,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (47,24,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (48,24,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (49,25,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (50,25,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (51,26,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (52,26,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (53,27,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (54,27,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (55,28,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (56,28,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (57,29,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (58,29,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (59,30,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (60,30,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (61,31,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (62,31,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (63,32,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (64,32,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (65,33,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (66,33,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (67,34,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (68,34,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (69,35,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (70,35,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (71,36,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (72,36,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (73,37,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (74,37,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (75,38,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (76,38,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (77,39,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (78,39,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (79,40,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (80,40,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (81,41,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (82,41,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (83,42,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (84,42,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (85,43,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (86,43,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (87,44,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (88,44,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (89,45,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (90,45,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (91,46,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (92,46,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (93,47,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (94,47,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (95,48,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (96,48,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (97,49,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (98,49,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (99,50,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (100,50,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (101,51,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (102,51,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (103,52,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (104,52,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (105,53,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (106,53,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (107,54,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (108,54,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (109,55,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (110,55,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (111,56,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (112,56,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (113,57,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (114,57,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (115,58,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (116,58,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (117,59,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (118,59,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (119,60,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (120,60,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (121,61,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (122,61,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (123,62,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (124,62,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (125,63,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (126,63,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (127,64,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (128,64,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (129,65,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (130,65,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (131,66,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (132,66,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (133,67,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (134,67,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (135,68,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (136,68,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (137,69,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (138,69,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (139,70,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (140,70,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (141,71,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (142,71,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (143,72,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (144,72,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (145,73,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (146,73,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (147,74,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (148,74,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (149,75,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (150,75,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (151,76,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (152,76,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (153,77,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (154,77,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (155,78,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (156,78,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (157,79,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (158,79,2,0,1);
INSERT INTO `prefix_lstest_scores` VALUES (159,80,1,0,0);
INSERT INTO `prefix_lstest_scores` VALUES (160,80,2,0,1);
